
import aws.AwsUtil;
import aws.UploadFile;
import static java.awt.SystemColor.text;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sandeep kumar
 */
public class EncryptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form EncryptionFrame
     */
    
     Files f = new Files();
     
    public EncryptionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fileName_tf = new javax.swing.JTextField();
        choose_bt = new javax.swing.JButton();
        encrypt_bt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileText_ta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        binary_ta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        level2_ta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        send_bt = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        level1_ta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encyption");
        setResizable(false);

        jLabel1.setText("File");

        fileName_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileName_tfActionPerformed(evt);
            }
        });

        choose_bt.setText("Choose");
        choose_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_btActionPerformed(evt);
            }
        });

        encrypt_bt.setText("Encrypt");
        encrypt_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_btActionPerformed(evt);
            }
        });

        fileText_ta.setColumns(20);
        fileText_ta.setLineWrap(true);
        fileText_ta.setRows(5);
        jScrollPane1.setViewportView(fileText_ta);

        jLabel2.setText("Content");

        binary_ta.setEditable(false);
        binary_ta.setColumns(20);
        binary_ta.setLineWrap(true);
        binary_ta.setRows(5);
        binary_ta.setWrapStyleWord(true);
        jScrollPane2.setViewportView(binary_ta);

        jLabel3.setText("Level_1");

        level2_ta.setEditable(false);
        level2_ta.setColumns(20);
        level2_ta.setLineWrap(true);
        level2_ta.setRows(5);
        level2_ta.setWrapStyleWord(true);
        jScrollPane3.setViewportView(level2_ta);

        jLabel4.setText("Level_2");

        send_bt.setText("SEND");
        send_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btActionPerformed(evt);
            }
        });

        level1_ta.setEditable(false);
        level1_ta.setColumns(20);
        level1_ta.setLineWrap(true);
        level1_ta.setRows(5);
        jScrollPane4.setViewportView(level1_ta);

        jLabel6.setText("Binary");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloud.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(encrypt_bt)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(saveBtn)
                                        .addGap(53, 53, 53)
                                        .addComponent(send_bt)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(fileName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choose_bt)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fileName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choose_bt)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(encrypt_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(send_bt)
                    .addComponent(saveBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileName_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileName_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileName_tfActionPerformed

    private void encrypt_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_btActionPerformed
       

           
     
         binary_ta.setText(f.toBinaryForm(fileText_ta.getText()));
         level1_ta.setText(f.toLevel1(binary_ta.getText()));
         try {
             level2_ta.setText(UtilClass.hexToBinary(f.toLevel2(level1_ta.getText())));
         } catch (IOException ex) {
             
         }
            
        
        
    }//GEN-LAST:event_encrypt_btActionPerformed

    private void choose_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_btActionPerformed
       JFileChooser j = new JFileChooser();
       FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
    j.setFileFilter(filter);
   int r = j.showOpenDialog(this);
    if (r == JFileChooser.APPROVE_OPTION) 
            { 
                // set the label to the path of the selected file 
                fileName_tf.setText(j.getSelectedFile().getAbsolutePath()); 
                String plainText = "";           
               plainText = f.getFileText(fileName_tf.getText());
                fileText_ta.setText(plainText);
            } 
            // if the user cancelled the operation 
            else
                fileName_tf.setText("NO FILE SELECTED");
    }//GEN-LAST:event_choose_btActionPerformed

    private void send_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btActionPerformed
       level2_ta.getText();
     
       DecriptionFrame df = new DecriptionFrame(level2_ta.getText());

       df.setVisible(true);
    }//GEN-LAST:event_send_btActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
      // setFrameEnabled(false);
      /*  
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            FinalEncryption.saveText(level2_ta.getText(),fileToSave);
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            
            //Save to cloud
            if(AwsUtil.saveFile(fileToSave.getAbsolutePath()))
                JOptionPane.showMessageDialog(this,"Successfully upload to cloud file name: "+fileToSave.getName());
        }
       */
     // String folderName = "C:\\Users\\Sandeep kumar\\Documents\\Cloud Storage";
      SaveCloud2 s = new SaveCloud2(this,this,level2_ta.getText());
      s.setVisible(true);
   /*   String fileName =  s.getFileName();
      String path = folderName+"\\"+fileName;
       setFrameEnabled(true);
        if(AwsUtil.saveFile(path))
                JOptionPane.showMessageDialog(this,"Successfully upload to cloud file name: "+fileName);
      */
   //s.setVisible(false);
     // setFrameEnabled(true);
    }//GEN-LAST:event_saveBtnActionPerformed

   public void setFrameEnabled(boolean b) {
        send_bt.setEnabled(b);
        saveBtn.setEnabled(b);
        encrypt_bt.setEnabled(b);
        choose_bt.setEnabled(b);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncryptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncryptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncryptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncryptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea binary_ta;
    private javax.swing.JButton choose_bt;
    private javax.swing.JButton encrypt_bt;
    private javax.swing.JTextField fileName_tf;
    private javax.swing.JTextArea fileText_ta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea level1_ta;
    private javax.swing.JTextArea level2_ta;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton send_bt;
    // End of variables declaration//GEN-END:variables
}
